# DIAS Homework 5

## Exponential of a matrix

In [6]:
import numpy as np 
import matplotlib.pyplot as plt 
import math
from numpy import linalg as LA
from tqdm.notebook import tqdm

In [13]:
#Function to find exponential using Taylor series to desired terms
def taylor_exponential(x, terms):
    ex=0
    for ii in range(terms):
        ex+=(x**ii)/(math.factorial(ii))
    return ex

#Function to find the 2D rotation matrix for a given theta
def rotation_matrix(x):
    return np.matrix([[np.cos(x),-np.sin(x)],[np.sin(x),np.cos(x)]])

# Pauli Matrices
Finding the imaginary exponential of the second Pauli Matrix with multiple prefactors 

Should have a similar format to the 2D rotation matrix

$$\begin{pmatrix} \cos{\alpha} & -\sin{\alpha} \\ \sin{\alpha} & \cos{\alpha} \end{pmatrix}$$

In [17]:
print(rotation_matrix(2))

[[-0.41614684 -0.90929743]
 [ 0.90929743 -0.41614684]]


In [29]:
#Pauli 2 matrix
pauli2=np.matrix([[1,0],[0,-1]])

#Generate multiple alphas
alpha=np.linspace(0,1,10)
for ii in alpha:
    rotation=rotation_matrix(ii)
    exponential=taylor_exponential((ii*pauli2)*1j, 15)
    print('For alpha =', ii, 
           '\n Imaginary exponential of 2nd Pauli matrix is \n', exponential,
         '\n and rotation matrix in 2D is \n', rotation, '. \n')

For alpha = 0.0 
 Imaginary exponential of 2nd Pauli matrix is 
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]] 
 and rotation matrix in 2D is 
 [[ 1. -0.]
 [ 0.  1.]] . 

For alpha = 0.1111111111111111 
 Imaginary exponential of 2nd Pauli matrix is 
 [[0.99383351+0.11088263j 0.        +0.j        ]
 [0.        +0.j         0.99383351-0.11088263j]] 
 and rotation matrix in 2D is 
 [[ 0.99383351 -0.11088263]
 [ 0.11088263  0.99383351]] . 

For alpha = 0.2222222222222222 
 Imaginary exponential of 2nd Pauli matrix is 
 [[0.97541009+0.22039774j 0.        +0.j        ]
 [0.        +0.j         0.97541009-0.22039774j]] 
 and rotation matrix in 2D is 
 [[ 0.97541009 -0.22039774]
 [ 0.22039774  0.97541009]] . 

For alpha = 0.3333333333333333 
 Imaginary exponential of 2nd Pauli matrix is 
 [[0.94495695+0.3271947j 0.        +0.j       ]
 [0.        +0.j        0.94495695-0.3271947j]] 
 and rotation matrix in 2D is 
 [[ 0.94495695 -0.3271947 ]
 [ 0.3271947   0.94495695]] . 

For alpha = 0.4444444444444444 